# Generated by Django 4.1.5 on 2023-02-05 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryTitle', models.CharField(db_index=True, max_length=250, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Справочник категорий',
                'ordering': ['categoryID'],
            },
        ),
        migrations.CreateModel(
            name='profilesIndex',
            fields=[
                ('profileIndex_PK', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('profileIndexTitle', models.CharField(db_index=True, max_length=250, verbose_name='Наименование Профиля')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Справочник профилей',
                'ordering': ['profileIndex_PK'],
            },
        ),
        migrations.CreateModel(
            name='subCategory',
            fields=[
                ('subCategoryID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategoryTitle', models.CharField(db_index=True, max_length=250, verbose_name='Наименование элемента')),
                ('subCategoryLink', models.TextField(verbose_name='Наименование элемента')),
            ],
            options={
                'verbose_name': 'Элемент категории',
                'verbose_name_plural': 'Справочник элементов ',
                'ordering': ['subCategoryID'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id'], 'verbose_name': 'Новость', 'verbose_name_plural': '1. НОВОСТИ'},
        ),
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('profileID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryID_FK', models.ForeignKey(db_column='categoryID_FK', on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='Категория')),
                ('profileIndex_FK', models.ForeignKey(db_column='profileIndex_FK', on_delete=django.db.models.deletion.PROTECT, to='news.profilesindex', verbose_name='Профиль')),
                ('subCategoryID_FK', models.ForeignKey(db_column='subCategoryID_FK', on_delete=django.db.models.deletion.PROTECT, to='news.subcategory', verbose_name='Элемент категории')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': '2. ПРОФИЛИ',
                'ordering': ['profileID'],
                'unique_together': {('profileIndex_FK', 'categoryID_FK', 'subCategoryID_FK')},
            },
        ),
        migrations.CreateModel(
            name='userRights',
            fields=[
                ('rightID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('profileID_FK', models.ForeignKey(db_column='profileID_FK', on_delete=django.db.models.deletion.PROTECT, to='news.profiles', verbose_name='Профиль')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Права',
                'verbose_name_plural': '3. ПРАВА ПОЛЬЗОВАТЕЛЕЙ',
                'ordering': ['userID'],
                'unique_together': {('userID', 'profileID_FK')},
            },
        ),
    ]
