# Generated by Django 4.1.5 on 2023-01-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
